[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_PRIVATE_BUILD_CACHE_DIR = ".next/cache"

[build.cache]
  paths = ["node_modules", ".next/cache"]
